### ISSUE TITLE
Data download Error.

### ISSUE THREAD

**Issue by jestarr** [keberwein/mlbgameday#3]
I'm getting an error message with my get payload command.

> innings_df <- get_payload(start = "2017-04-03", end = "2017-04-04")
Gathering Gameday data, please be patient...
Error: `by` can't contain join column `batter` which is missing from LHS

**Comment by keberwein** [comment]
Thanks for pointing that out. I was aware of that bug and it has been fixed in version 0.1.0. I have not pushed this version to CRAN yet, but you can install it from the git repo. I highly recommend upgrading to the new version as there were several other bug fixes as well.

`devtools::install_github("keberwein/mlbgameday")`

Again, I apologize, I was hoping to get this version to CRAN before the season started, but Spring Training snuck up on my very quickly this year!

**EDIT:** I deployed the new version to CRAN today. Just update the package and you're all set.
